spring.datasource.url=jdbc:mysql://localhost:3306/recette
spring.datasource.username=root
spring.datasource.password=2001HAJHOUJREALMADRID$$$$

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true